### ISSUE TITLE
vdr-plugin-femon does not build with vdr-2.7.1

### ISSUE THREAD

**Issue by madmartin** [rofafor/vdr-plugin-femon#7]
Compiling femon plugin against vdr-2.7.1 fails:

```
femon.c: In member function ‘virtual cOsdObject* cPluginFemon::MainMenuAction()’:
femon.c:124:24: error: no matching function for call to ‘cControl::Control()’
  124 |   if (cControl::Control() || (Channels->Count() <= 0))
      |       ~~~~~~~~~~~~~~~~~^~
In file included from /usr/include/vdr/dvbplayer.h:13,
                 from /usr/include/vdr/menu.h:17,
                 from femon.c:9:
/usr/include/vdr/player.h:129:20: note: candidate: ‘static cControl* cControl::Control(cMutexLock&, bool)’
  129 |   static cControl *Control(cMutexLock &MutexLock, bool Hidden = false);
      |                    ^~~~~~~
/usr/include/vdr/player.h:129:20: note:   candidate expects 2 arguments, 0 provided

```
The changelog of vdr-2.7.1 says:

- The default for DEPRECATED_CCONTROL has been set to 0, which means that
  the function Control(bool Hidden) is no longer available.
  You can add 'DEPRECATED_CCONTROL=1' when compiling in order to restore this
  functionality. However, it is recommended to use Control(cMutexLock &MutexLock, bool Hidden)
  instead.

**Comment by rofafor** [comment]
Sorry, I don't have any vdr hardware available at this time and therefore my vdr related projects has been living in suspended mode for a few years already. Please, don't hold your breath for a fix unless someone sends a pull request

**Comment by bacardischmal** [comment]
Hello,
i found this patch to remove the deprecated interfaces function, maybe you can implement this if the functions are not needed?

https://www.vdr-portal.de/index.php?attachment/49666-0002-femon-removal-of-deprecated-interface-functions-zip/
