### ISSUE TITLE
Compile with 2.3.2

### ISSUE THREAD

**Issue by jsffm** [rofafor/vdr-plugin-femon#3]
During compile with vdr-2.3.2 I get following messages:

In file included from /usr/local/vdr/vdr-2.3.2/include/vdr/config.h:20:0,
                 from /usr/local/vdr/vdr-2.3.2/include/vdr/channels.h:13,
                 from /usr/local/vdr/vdr-2.3.2/include/vdr/device.h:13,
                 from /usr/local/vdr/vdr-2.3.2/include/vdr/receiver.h:13,
                 from receiver.h:12,
                 from osd.c:18:
/usr/local/vdr/vdr-2.3.2/include/vdr/font.h:48:15: error: ‘virtual int cFont::Width() const’ was hidden [-Werror=overloaded-virtual]
   virtual int Width(void) const = 0;
               ^
osd.c:148:15: error:   by ‘cFemonDummyFont::Width’ [-Werror=overloaded-virtual]
   virtual int Width(const char *sP) const { return 50; }
               ^
osd.c: In constructor ‘cFemonOsd::cFemonOsd()’:
osd.c:209:18: error: invalid new-expression of abstract class type ‘cFemonDummyFont’
      fontM = new cFemonDummyFont;
                  ^
osd.c:145:7: note:   because the following virtual functions are pure within ‘cFemonDummyFont’:
 class cFemonDummyFont : public cFont {
       ^
In file included from /usr/local/vdr/vdr-2.3.2/include/vdr/config.h:20:0,
                 from /usr/local/vdr/vdr-2.3.2/include/vdr/channels.h:13,
                 from /usr/local/vdr/vdr-2.3.2/include/vdr/device.h:13,
                 from /usr/local/vdr/vdr-2.3.2/include/vdr/receiver.h:13,
                 from receiver.h:12,
                 from osd.c:18:
/usr/local/vdr/vdr-2.3.2/include/vdr/font.h:48:15: note:        virtual int cFont::Width() const
   virtual int Width(void) const = 0;
               ^
cc1plus: some warnings being treated as errors
Makefile:73: recipe for target 'osd.o' failed
make: *** [osd.o] Error 1

**Comment by rofafor** [comment]
Please, take a look at this: https://linuxtv.org/pipermail/vdr/2016-December/029182.html

**Comment by jsffm** [comment]
Now it compiles, thankyou.
